//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Medicine_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string Customer_Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public int MedicId { get; set; }
        public string Medicine_Description { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
